version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: t3practice
      POSTGRES_PASSWORD: t3practice
      POSTGRES_DB: t3practice
    restart: always
    networks:
      - lesson
networks:
  lesson: